version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: submita_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: submita_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network
    restart: unless-stopped

  # MinIO para armazenamento de arquivos
  minio:
    image: minio/minio
    container_name: local-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - auth-network
    restart: unless-stopped

  # MinIO para criar buckets automaticamente e configurar políticas de acesso
  minio-setup:
    image: minio/mc:latest
    container_name: submita_minio_setup
    depends_on:
      - minio
    networks:
      - auth-network
    entrypoint: >
      /bin/sh -c "
      echo 'Aguardando MinIO inicializar...';
      sleep 10;
      mc alias set myminio http://local-minio:9000 minioadmin minioadmin;
      mc mb myminio/submita-files --ignore-existing;
      mc mb myminio/submita-pdfs --ignore-existing;
      mc mb myminio/submita-images --ignore-existing;
      # Define a política de leitura pública para o bucket de imagens
      mc anonymous set download myminio/submita-pdfs;
      mc anonymous set download myminio/submita-images;
      echo 'Buckets criados e políticas configuradas com sucesso!';
      exit 0;
      "

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  auth-network:
    driver: bridge
